import Head from "next/head"
import Link from "next/link"
import Image from "next/image"
import { callContentful, getPostList } from "../utils/contentful-api"
import PublishedDate from "../components/PublishedDate"
import {
  formatPublishedDateForDisplay,
  formatPublishedDateForDateTime,
} from "../utils/date"

export default function Home({ recentPostList }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {recentPostList.map((post) => (
          <div className="px-6 my-6" key={post.sys.id}>
            <Link href={`/articles/${post.slug}`}>
              <a>
                <Image
                  src={post.heroImage.url}
                  alt={post.heroImage.description}
                  width={post.heroImage.width}
                  height={post.heroImage.height}
                  layout="responsive"
                />
                <PublishedDate
                  date={post.date}
                  datetime={post.datetime}
                  styles=" text-sm text-left mb-1 mt-4"
                />
                <h2 className="mb-2">{post.title}</h2>
                <p className="text-base">{post.excerpt}</p>
              </a>
            </Link>
          </div>
        ))}
        <Link href="/articles">
          <a>View All Articles</a>
        </Link>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const response = await callContentful(getPostList, { limit: 7 })
  const recentPostList = response.data.blogPostCollection.items

  recentPostList.map((post, index) => {
    recentPostList[index].date = formatPublishedDateForDisplay(post.date)
    recentPostList[index].datetime = formatPublishedDateForDateTime(post.date)
  })

  return {
    props: {
      recentPostList,
    },
  }
}
