import Head from "next/head"
import Link from "next/link"
import { callContentful, getPostList } from "../utils/contentful-api"
import PublishedDate from "../components/PublishedDate"
import {
  formatPublishedDateForDisplay,
  formatPublishedDateForDateTime,
} from "../utils/date"

export default function Home({ recentPostList }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {recentPostList.map((post) => (
          <div key={post.sys.id}>
            <Link href={`/articles/${post.slug}`}>
              <a>
                <h1>{post.title}</h1>
              </a>
            </Link>
            <p>{post.excerpt}</p>
            <PublishedDate date={post.date} datetime={post.datetime} />
          </div>
        ))}
        <Link href="/articles">
          <a>See All Articles</a>
        </Link>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const response = await callContentful(getPostList, { limit: 2 })
  const recentPostList = response.data.blogPostCollection.items

  recentPostList.map((post, index) => {
    
    recentPostList[index].date = formatPublishedDateForDisplay(post.date)
    recentPostList[index].datetime = formatPublishedDateForDateTime(post.date)

  })

  console.log(recentPostList)

  return {
    props: {
      recentPostList,
    },
  }
}
